on:
  push:
    tags:
      - 'v*'
    branch: [otv]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build
      - run: npm run bundle
      - id: version
        uses: release-kit/semver@v2
      - run: npm version ${{ steps.version.outputs.full }}
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"

