name: Release
on: [pull_request]
# on:
#   push:
#     tags:
#       - 'v*'
#     branch: [otv]

jobs:
  release:
    runs-on: [self-hosted, runner-linux-docker]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build
      - run: npm run bundle
      # - id: version
      #   uses: release-kit/semver@v2
      # - run: npm pkg set version=${{ steps.version.outputs.full }}
      # - uses: JS-DevTools/npm-publish@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     registry: "https://npm.pkg.github.com"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: playground
          path: ./playground/dist
          retention-days: 1
          compression-level: 0


  publish-playground:
    runs-on: [self-hosted, docs-linux-docker]
    needs: [release]
    steps:
      - name: Ensure empty playground directory
        run: rm -rf /otv-public-html && mkdir -p /otv-public-html
      - name: Download playground artifact
        uses: actions/download-artifact@v4
        with:
          name: playground
          path: /otv-public-html


