name: Review
on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build
      - run: npm run bundle
      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: otv
          path: ${{ github.workspace }}/dist
          retention-days: 5
      - uses: mshick/add-pr-comment@v2
        with:
          message-id: oscode-preview-artifact
          message: |
            [📦 OTV Preview](${{ steps.artifact-upload.outputs.artifact-url }})

